language: node_js
node_js:
  - '10'
sudo: false
cache:
  yarn: true
  directories:
    - node_modules
script:
  - yarn
  - yarn build
before_deploy:
  - pip install --user awscli
# deploy:
#   provider: s3
#   access_key_id:
#     secure: "W1/4ZOjexCo2WSQIwP2+1tB0/ySpyCXLHjsODdiU5kSTH2sqGhB4+h2Wvr51Krz3SBhyT6FB6H1ZAu1jspU+EYdVOWHGi8V12JTUOTUgAvxO8Du4GFAeThpvr7bOhwEr6PZdnIYqTCUR7zac0YWZssEDgbxlbHCOWP6NPvAlkPt5PKwYKPfIfx/VGZtIxvjFe3PE2H3ZwPp4ZoDXgWJeU3B/+mqHEq7+mwBbyWzUSBTvAoBRm9Qh0CYAVhEVLvt9Nmuu8+se/Gx8dsCljuN0/LifMmkh++VWgN6h24YuI4jGxa1P/r9RdPlx43IfTN5wE7L8QwudvLfuG3Y04t+LK99dv0l0ghq3vLKjEVxqHqtSs4hazBzKm+ePKFLNIygybOReR3FVFgMsWxIkpvEYv5hf8hIno5MDlnL5cMT00wtNeGuu08MhHjx0GzR0GlpNWZqJLu1LwYRNSS2TIyY80td3QAB7wC5FURlQNTCmvyeeiUaqaQQ7AZA2TRrXMZLQw9lBZmMOdyyxkN7nYtujyruphPloKScKs3rM3SZaNPzLunP8OxM7zDKB7aP3U9bIb6zGvw/kN+3dF8hX+1qcjrSo99vlk9huV8XDePicRvqjdfjcIPPeC1hgLoqPPDICM3vehtOfimuTdcETTbFK1avVjxW7X9muvPw/K4WXAPs="
#   secret_access_key:
#     secure: "nmB9JclrFAM5DII84Eb1WhkYzd3JRqg/EmNz+lhtEBcBv/e4u2XSwm2uFkTvdGAxJfD/z1HDzD+zUZljVTMk4NQCww10LQnf5gaU/nV3I4/krzYLeDDWxQY8Mnm22ID9LLC3IyypFoY+qEjEqh2GWrz6sUUU6uTR6onfxfhgDHJWwMIK+ACPQOiAsFY9LZahOgqmpl+YqjYzgKsOfYGnrCDU2v6PDh158SJ8QcKxcSkuAMa2JA17eMPY8ge/ixNzg8igDg5iTUE6NRpp4yYLvkw8g2KvVE9jaPEXQQEQ2OLvoN55R51+HvPhhV/BpyPdbug30bdCxn5lliNcfXOIzUQwtsJM4vGD8w603sqfZSgsjeqBLysym+LgPPnxthrb0jzE4BPEqG+rvg+NxrGJJHn5+D2h3gHnKpSdnDOsx0RlgXAe/YjLzwR/IP/EpO7cy4HE981NJX1d7wRbhRsDVD/a9j4A2Tv+iZgWq16IqxYo8fO5uWhmKiZ/I/rgGfiHw7RFYslVH4Ohdff+tfMQ3hXpiOSxijv4RI7b5r5rK/VoMTOYEzhgbvFeQbM093R5ctTA/5u3/aQ+fER5DFH4h4PFt53hhj+aiFcyQ+B+Sy9kw13Pb1XZrtSijLkvAd6MPaOXYusliL0KGhakdovMxGph9LwSOeS1epD4NkpZb2Y="
#   bucket: todo.diogocardoso.me
#   skip_cleanup: true
#   region: eu-west-2
#   local_dir: build
deploy:
  provider: script
  script: ~/.local/bin/aws s3 sync build s3://todo.diogocardoso.me --region=eu-west-2 --delete
  skip_cleanup: true
  on:
    branch: master
notifications:
  email: false
env:
    global:
          - secure: "RvgtU5+v+/t//Ew2Z48oAYkoJSzBjpYEo3yXSfXRF0uKM2QgQklcKlxCbog2HtPYI3WDP8gkol+L8VmlvNuM2WQzcQ6L8+D1qJtZ0IGAdI9d4IfU6kQgoQjN6Y8y1RhHKiPp6k+DvgU24InrDAZv+oXNwyhtysExIGUHOea1DuKbEfTBVotNfNOSSHHTdR0TwpZ9cW8RU6z1nxAEXfN6ymGsZyiqQ+jbbVrT2H9+rfXuClwlNlEKrJpDauf9SjtLiHUJkgfzNBHhhP3oPQox2VKdNyXdBdeg963UFSIB9zrjNpYV0KqSojHPF+zn3cyT3vYwmKmgbUyNtldSQWD4nrdKCnFRka9gKbr2WX/9fbQMOaZ+IAD2bFjY70Y80L1NLTVpx62pBzjtkbKSBmGLXJ7wkW0PH9KkUo73p0dZxkKxV0HXURUvZzSKxTmOUfczqDwgAMsh+x2NLceye+EMQJl0D6RUOv5Opr7r1d4lh2UlWORvbEi9GwQvCviVtTc77L3Ks/EtfEAGDtYxXm5N9Fd7Bnz7dVUmVlvFCcmLLdFGVvogZud2WtMszEqHxlXhPqXQoC0QcOHh7AqYUADIxXUFXFASJaDZFDJ7tWmmUhtH6nfYhhSvZjNyN1RCR5DMd9iYpVS98+iT0BhCCeCkV96l/uUhFJMe7nMakjHpW8s="
          - secure: "bkYfHMsMm7nZ1hrD2o9gyAZ7Cg2ewzKFZKZrzPwEz5W7S88akZKTMJNqnE+r6V1R46baHnred7avn1Zgfs8lUlHLJ7iOue+eTqQ+JMwZErMzLrFL7Ni00nRYo3kZ62Y0zv64XZGgefhVa1CVDa8g8sZcdZhlRbU3APBSHPgr67tVpyFKVpr8My3eXPEdLrRgNnhn+dtThOhbAkD/gZaLYpwMhKap7oV5+8y/MDJP04z29HBYLqo8KUkw452q2vrDd0h6qpT7rXI9ACfTqMQ6tRVQWeFaH3aCa4jIkzdbsVI0VvRSZqHWt+N4vJ/tag7li9WypViKNTxHnNmaBHLP/fclO1vFHc5A0+Vdn8Zr7CP2+TkAVvfwKrTH5H2hJXkfiIW6PMwDh0aHXIdCR8iK8WcG4oRIQnCjeDXMYmDkwPBhZNoJL6APRyFh0tgemNU2lkEuWTOFcttjhJm1bql2onLfhR0nvNydh/CpDftJZ3ikF0MYeUQ/6cBF+rGKXKxvGzHQAbD9GK5Mrbu2gesoCCIXqjwf71f1iWmU6HODjz9rtNEJARkl41fWgyd35mNxuJ67lyHLPeO8Z3yaf5mBd8FW5vuUOhVOphhKgl/sp+GhgK4XKhzG0VvIrjk63z4/x93LM4NB58RNCmnRyVk/rf5HSWXm2LpEUl8sVZKqY6k="